import json
import os
import pandas as pd

special_char = {
    "x": "xs",
    "s": "sx",
    "d": "drg",
    "r": "rdg",
    "g": "grd",
    "ch": "tr",
    "tr": "ch",
    "n": "l",
    "l": "n",
}

vietnamese_characters = [
    "á",
    "à",
    "ả",
    "ã",
    "ạ",
    "ă",
    "ắ",
    "ằ",
    "ẳ",
    "ẵ",
    "ặ",
    "â",
    "ấ",
    "ầ",
    "ẩ",
    "ẫ",
    "ậ",
    "é",
    "è",
    "ẻ",
    "ẽ",
    "ẹ",
    "ê",
    "ế",
    "ề",
    "ể",
    "ễ",
    "ệ",
    "í",
    "ì",
    "ỉ",
    "ĩ",
    "ị",
    "ó",
    "ò",
    "ỏ",
    "õ",
    "ọ",
    "ô",
    "ố",
    "ồ",
    "ổ",
    "ỗ",
    "ộ",
    "ơ",
    "ớ",
    "ờ",
    "ở",
    "ỡ",
    "ợ",
    "ú",
    "ù",
    "ủ",
    "ũ",
    "ụ",
    "ư",
    "ứ",
    "ừ",
    "ử",
    "ữ",
    "ự",
    "ý",
    "ỳ",
    "ỷ",
    "ỹ",
    "ỵ",
    "đ",
]
# sac, huyen, hoi, nga, nang, mu, rau, mu nguoc :>
special_token_sign_vietnamese = {
    "sac": "<´>",
    "huyen": "<`>",
    "hoi": "<?>",
    "nga": "<~>",
    "nang": "<.>",
    "mu": "<^>",
    "rau": "<,>",
    "mu_nguoc": "<^^>",
}
convert_char_vietnamese = {
    "á": ("a", special_token_sign_vietnamese["sac"]),
    "à": ("a", special_token_sign_vietnamese["huyen"]),
    "ả": ("a", special_token_sign_vietnamese["hoi"]),
    "ã": ("a", special_token_sign_vietnamese["nga"]),
    "ạ": ("a", special_token_sign_vietnamese["nang"]),
    "ă": ("a", special_token_sign_vietnamese["mu_nguoc"]),
    "ắ": (
        "a",
        special_token_sign_vietnamese["mu_nguoc"],
        special_token_sign_vietnamese["sac"],
    ),
    "ằ": (
        "a",
        special_token_sign_vietnamese["mu_nguoc"],
        special_token_sign_vietnamese["huyen"],
    ),
    "ẳ": (
        "a",
        special_token_sign_vietnamese["mu_nguoc"],
        special_token_sign_vietnamese["hoi"],
    ),
    "ẵ": (
        "a",
        special_token_sign_vietnamese["mu_nguoc"],
        special_token_sign_vietnamese["nga"],
    ),
    "ặ": (
        "a",
        special_token_sign_vietnamese["mu_nguoc"],
        special_token_sign_vietnamese["nang"],
    ),
    "â": ("a", special_token_sign_vietnamese["mu"]),
    "ấ": (
        "a",
        special_token_sign_vietnamese["mu"],
        special_token_sign_vietnamese["sac"],
    ),
    "ầ": (
        "a",
        special_token_sign_vietnamese["mu"],
        special_token_sign_vietnamese["huyen"],
    ),
    "ẩ": (
        "a",
        special_token_sign_vietnamese["mu"],
        special_token_sign_vietnamese["hoi"],
    ),
    "ẫ": (
        "a",
        special_token_sign_vietnamese["mu"],
        special_token_sign_vietnamese["nga"],
    ),
    "ậ": (
        "a",
        special_token_sign_vietnamese["mu"],
        special_token_sign_vietnamese["nang"],
    ),
    "é": ("e", special_token_sign_vietnamese["sac"]),
    "è": ("e", special_token_sign_vietnamese["huyen"]),
    "ẻ": ("e", special_token_sign_vietnamese["hoi"]),
    "ẽ": ("e", special_token_sign_vietnamese["nga"]),
    "ẹ": ("e", special_token_sign_vietnamese["nang"]),
    "ê": ("e", special_token_sign_vietnamese["mu"]),
    "ế": (
        "e",
        special_token_sign_vietnamese["mu"],
        special_token_sign_vietnamese["sac"],
    ),
    "ề": (
        "e",
        special_token_sign_vietnamese["mu"],
        special_token_sign_vietnamese["huyen"],
    ),
    "ể": (
        "e",
        special_token_sign_vietnamese["mu"],
        special_token_sign_vietnamese["hoi"],
    ),
    "ễ": (
        "e",
        special_token_sign_vietnamese["mu"],
        special_token_sign_vietnamese["nga"],
    ),
    "ệ": (
        "e",
        special_token_sign_vietnamese["mu"],
        special_token_sign_vietnamese["nang"],
    ),
    "í": ("i", special_token_sign_vietnamese["sac"]),
    "ì": ("i", special_token_sign_vietnamese["huyen"]),
    "ỉ": ("i", special_token_sign_vietnamese["hoi"]),
    "ĩ": ("i", special_token_sign_vietnamese["nga"]),
    "ị": ("i", special_token_sign_vietnamese["nang"]),
    "ó": ("o", special_token_sign_vietnamese["sac"]),
    "ò": ("o", special_token_sign_vietnamese["huyen"]),
    "ỏ": ("o", special_token_sign_vietnamese["hoi"]),
    "õ": ("o", special_token_sign_vietnamese["nga"]),
    "ọ": ("o", special_token_sign_vietnamese["nang"]),
    "ô": ("o", special_token_sign_vietnamese["mu"]),
    "ố": (
        "o",
        special_token_sign_vietnamese["mu"],
        special_token_sign_vietnamese["sac"],
    ),
    "ồ": (
        "o",
        special_token_sign_vietnamese["mu"],
        special_token_sign_vietnamese["huyen"],
    ),
    "ổ": (
        "o",
        special_token_sign_vietnamese["mu"],
        special_token_sign_vietnamese["hoi"],
    ),
    "ỗ": (
        "o",
        special_token_sign_vietnamese["mu"],
        special_token_sign_vietnamese["nga"],
    ),
    "ộ": (
        "o",
        special_token_sign_vietnamese["mu"],
        special_token_sign_vietnamese["nang"],
    ),
    "ơ": ("o", special_token_sign_vietnamese["rau"]),
    "ớ": (
        "o",
        special_token_sign_vietnamese["rau"],
        special_token_sign_vietnamese["sac"],
    ),
    "ờ": (
        "o",
        special_token_sign_vietnamese["rau"],
        special_token_sign_vietnamese["huyen"],
    ),
    "ở": (
        "o",
        special_token_sign_vietnamese["rau"],
        special_token_sign_vietnamese["hoi"],
    ),
    "ỡ": (
        "o",
        special_token_sign_vietnamese["rau"],
        special_token_sign_vietnamese["nga"],
    ),
    "ợ": (
        "o",
        special_token_sign_vietnamese["rau"],
        special_token_sign_vietnamese["nang"],
    ),
    "ú": ("u", special_token_sign_vietnamese["sac"]),
    "ù": ("u", special_token_sign_vietnamese["huyen"]),
    "ủ": ("u", special_token_sign_vietnamese["hoi"]),
    "ũ": ("u", special_token_sign_vietnamese["nga"]),
    "ụ": ("u", special_token_sign_vietnamese["nang"]),
    "ư": ("u", special_token_sign_vietnamese["rau"]),
    "ứ": (
        "u",
        special_token_sign_vietnamese["rau"],
        special_token_sign_vietnamese["sac"],
    ),
    "ừ": (
        "u",
        special_token_sign_vietnamese["rau"],
        special_token_sign_vietnamese["huyen"],
    ),
    "ử": (
        "u",
        special_token_sign_vietnamese["rau"],
        special_token_sign_vietnamese["hoi"],
    ),
    "ữ": (
        "u",
        special_token_sign_vietnamese["rau"],
        special_token_sign_vietnamese["nga"],
    ),
    "ự": (
        "u",
        special_token_sign_vietnamese["rau"],
        special_token_sign_vietnamese["nang"],
    ),
    "ý": ("y", special_token_sign_vietnamese["sac"]),
    "ỳ": ("y", special_token_sign_vietnamese["huyen"]),
    "ỷ": ("y", special_token_sign_vietnamese["hoi"]),
    "ỹ": ("y", special_token_sign_vietnamese["nga"]),
    "ỵ": ("y", special_token_sign_vietnamese["nang"]),
    "đ": ("d", "d"),
}


def write_dict_data_to_file(file_path, data, indent=2):
    with open(file_path, "w", encoding="utf-8") as outfile:
        json.dump(data, outfile, ensure_ascii=False, indent=indent)


def write_list_data_to_file(file_path, list_data):
    # os.makedirs(file_path, exist_ok=True)
    with open(file=file_path, mode="w", encoding="utf-8") as file:
        file.write("".join([x + "\n" for x in list_data]))
